Misiug/fixarmpython (#244)
On ARM machines, conda's version of python3.12 is broken and hits this
error when you try to activate the environment:
```
Activating conda environment
Traceback (most recent call last):
  File "/raid/misiug/velox-testing/presto/scripts/.venv/bin/pip", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/raid/misiug/velox-testing/presto/scripts/.venv/lib/python3.12/site-packages/pip/_internal/cli/main.py", line 47, in main
    from pip._internal.cli.autocompletion import autocomplete
  File "/raid/misiug/velox-testing/presto/scripts/.venv/lib/python3.12/site-packages/pip/_internal/cli/autocompletion.py", line 12, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/raid/misiug/velox-testing/presto/scripts/.venv/lib/python3.12/site-packages/pip/_internal/cli/main_parser.py", line 6, in <module>
    import subprocess
  File "/usr/lib/python3.12/subprocess.py", line 104, in <module>
    from _posixsubprocess import fork_exec as _fork_exec
ModuleNotFoundError: No module named '_posixsubprocess'
```

Our deps generally require python3.11 or higher, so default to 3.11 in
this context.

---------

Co-authored-by: Misiu Godfrey <misiug@lego-cg1-qs-185.aselab.nvidia.com>